### ISSUE TITLE
Some bugs and recomandations for improvements

### ISSUE THREAD

**Issue by MelalDev** [Mr30nama/30nama-Hybrid#2]
Thanks for your good services , Here is the tought of my own experience as one of your clients:

bugs:

-  Advanced search works for the first time ,but if you click one of the items and plays it for a while, hit back button twice to get back to the root , change the paramters of search, hit the search button ,  no longer it applys the correct result 

improvements : 

- After clicking on one item , it shows the crew list , it's not clickable , it's much more convinient to click an actor or actress to redirect to the advanced search and see related movies and tv shows.

- in advanced serach , if you scroll multiple pages and click one of the items, and hit back , then it requires you scroll back the previous location . suppose you scrolled 10 pages , click on one item , you will find out it's not interesting for you , hit back , then you need to scrool 10 pages again to get back to the previous location

- in previous version , you could see the comments , it not longer exist.

regards

**Comment by MelalDev** [comment]
- in dashboard , the "Our Suggestion" section , there is no button for back or forward , suppose one item catch your eyes but before deciding it swtitch to another item, then the user have to wait for a long time to see that itme again. I suppose a back and forward and pause button would be helpfull.

-some of the movies or tv shows doesn't have subtitle , That would be helpfull if user can add it's own subtitle for it's own watch.

- in search and advanced ( precise) search , it would be greate if you can click an item as a modal form for seeing the details and if user close the form , it can proceed browing other items.

**Comment by EternalC0der** [comment]
Hello,

1. I just checked the advanced search, and it works as expected, would you give me more details?

2. actors and actresses will be clickable after the new infrastructure is finished for casts and crew (we will have a dedicated section for their biography and discography)

3. quick solution would be to change infinite scrolling to pagination in settings

4. as I said in #2 our new infrastructure is still heavily under development, and we have other concerns to take care about than comments for now. It'll be ready asap.

5. Good one, will add next and previous option in upcoming 0.13.1 - 0.14.0 versions.

6. We'll see what we can do about that.

7. I don't think this one is necessary because you can just click on an item, see it details and click on back..
